Repository rhobs/observability-operator, pull requests merged in 2023-09, with the labels that each got.

#351 chore: add OWNERS files
  OWNERS
  OWNERS_ALIASES
  cmd/OWNERS
  docs/OWNERS
  jsonnet/OWNERS
  pkg/OWNERS
  test/OWNERS
Labels: lgtm

#341 MON-3355: build: build and publish test harness images in release workflow
  .github/osd-test-harness-publish/action.yaml
  .github/workflows/release.yaml
Labels: lgtm, jira/valid-reference, approved

#353 ci: build test-harness for dev releases
  .github/workflows/release.yaml
Labels: lgtm, approved

#350 ci: use go version in go.mod file
  .github/e2e-tests-olm/action.yaml
  .github/env
  .github/olm-publish/action.yaml
  .github/osd-test-harness-publish/action.yaml
  .github/package-operator-publish/action.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/release.yaml
Labels: lgtm, approved

#361 chore: update operator-sdk v1.31.0
  .github/tools
  Makefile
  Makefile.tools
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  go.sum
Labels: lgtm, approved

#354 MON-2708: remove ServiceMonitor observability-operator from bundle
  bundle/manifests/observability-operator_monitoring.coreos.com_v1_servicemonitor.yaml
  deploy/operator/kustomization.yaml
  deploy/operator/observability-operator-service-monitor.yaml
Labels: lgtm, jira/valid-reference, approved

#360 ci: bundle dockerfile is needed for prow job
  .gitignore
  bundle.Dockerfile
Labels: lgtm, approved

#362 fix: remove stripped down crds hack
  bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
  bundle/manifests/monitoring.rhobs_alertmanagers.yaml
  bundle/manifests/monitoring.rhobs_podmonitors.yaml
  bundle/manifests/monitoring.rhobs_probes.yaml
  bundle/manifests/monitoring.rhobs_prometheusagents.yaml
  bundle/manifests/monitoring.rhobs_prometheuses.yaml
  bundle/manifests/monitoring.rhobs_prometheusrules.yaml
  bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
  bundle/manifests/monitoring.rhobs_servicemonitors.yaml
  bundle/manifests/monitoring.rhobs_thanosrulers.yaml
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/dependencies/kustomization.yaml
Labels: lgtm, approved

#365 chore: drop defunct team from CODEOWNERS
  CODEOWNERS
  bundle.Dockerfile
Labels: lgtm, approved
