Repository rhobs/observability-operator, pull requests merged in 2024-10, with the labels that each got.

#578 COO-402: update to Prometheus operator v0.77.1
  bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
  bundle/manifests/monitoring.rhobs_alertmanagers.yaml
  bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
  bundle/manifests/monitoring.rhobs_podmonitors.yaml
  bundle/manifests/monitoring.rhobs_probes.yaml
  bundle/manifests/monitoring.rhobs_prometheusagents.yaml
  bundle/manifests/monitoring.rhobs_prometheuses.yaml
  bundle/manifests/monitoring.rhobs_prometheusrules.yaml
  bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
  bundle/manifests/monitoring.rhobs_servicemonitors.yaml
  bundle/manifests/monitoring.rhobs_thanosrulers.yaml
  bundle/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml
  bundle/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml
  bundle/manifests/obo-prometheus-operator_v1_service.yaml
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
  deploy/dependencies/kustomization.yaml
  docs/api.md
  go.mod
  go.sum
  pkg/controllers/monitoring/monitoring-stack/components.go
  test/e2e/monitoring_stack_controller_test.go
Labels: lgtm, jira/valid-reference, approved

#579 chore(release): 0.4.1
  CHANGELOG.md
  VERSION
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/kustomization.yaml
  deploy/package-operator/operator/kustomization.yaml
Labels: lgtm, approved

#496 feat: TLS support for the Thanos web endpoint
  bundle/manifests/monitoring.rhobs_thanosqueriers.yaml
  deploy/crds/common/monitoring.rhobs_thanosqueriers.yaml
  docs/api.md
  pkg/apis/monitoring/v1alpha1/types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/monitoring/thanos-querier/components.go
  pkg/controllers/monitoring/thanos-querier/controller.go
  test/e2e/thanos_querier_controller_test.go
Labels: lgtm, approved, ok-to-test

#582 Revert "feat: TLS support for the Thanos web endpoint"
  bundle/manifests/monitoring.rhobs_thanosqueriers.yaml
  deploy/crds/common/monitoring.rhobs_thanosqueriers.yaml
  docs/api.md
  pkg/apis/monitoring/v1alpha1/types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/monitoring/thanos-querier/components.go
  pkg/controllers/monitoring/thanos-querier/controller.go
  test/e2e/thanos_querier_controller_test.go
Labels: lgtm, approved

#581 COO-451: fix: use expected plugin console names
  pkg/controllers/uiplugin/plugin_info_builder.go
Labels: lgtm, jira/valid-reference, approved

#577 chore: use fmt.Sprintf for YAML generation
  pkg/controllers/monitoring/monitoring-stack/components.go
  pkg/controllers/monitoring/monitoring-stack/components_test.go
  pkg/controllers/monitoring/monitoring-stack/testdata/no-tls
  pkg/controllers/monitoring/monitoring-stack/testdata/tls
  test/e2e/framework/prometheus_client.go
  test/e2e/monitoring_stack_controller_test.go
Labels: lgtm, approved

#594 chore: add job to run unit tests
  .github/workflows/pr-checks.yaml
  pkg/controllers/monitoring/monitoring-stack/testdata/tls
Labels: lgtm, approved

#593 ci: don't commitlint konflux commits
  commitlint.config.mjs
Labels: lgtm, approved

#596 chore: update GitHub actions
  .github/e2e-tests-olm/action.yaml
Labels: lgtm, approved

#597 feat: add Trace support in korrel8r
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/config/korrel8r.yaml
  pkg/controllers/uiplugin/plugin_info_builder.go
  pkg/controllers/uiplugin/troubleshooting_panel.go
Labels: lgtm, approved

#575 OU-407: Add monitoring-plugin uiplugin
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  cmd/operator/main.go
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  docs/api.md
  docs/user-guides/observability-ui-plugins.md
  go.mod
  go.sum
  pkg/apis/uiplugin/v1alpha1/types.go
  pkg/apis/uiplugin/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/compatibility_matrix_test.go
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/monitoring.go
  pkg/controllers/uiplugin/plugin_info_builder.go
  pkg/operator/scheme.go
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#605 COO-474: fix: hide Prometheus operator CRDs in UI
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/bases/observability-operator.clusterserviceversion.yaml
Labels: lgtm, jira/valid-reference, approved

#610 chore: bump operator-sdk version
  .github/e2e-tests-olm/action.yaml
  .github/tools
  Makefile.tools
  bundle.Dockerfile
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
Labels: lgtm, approved

#595 COO-480: feat: enable HTTPS in OpenShift clusters
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability-operator_v1_service.yaml
  cmd/operator/main.go
  deploy/operator/observability-operator-deployment.yaml
  deploy/operator/observability-operator-service.yaml
  go.mod
  go.sum
  pkg/operator/operator.go
  test/e2e/framework/assertions.go
  test/e2e/framework/framework.go
  test/e2e/main_test.go
  test/e2e/metrics_test.go
  test/e2e/uiplugin_test.go
Labels: lgtm, jira/valid-reference, approved

#604 COO-318: add uiplugin support annotations when created
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/plugin_info_builder.go
Labels: lgtm, jira/valid-reference, approved, needs-ok-to-test

#608 fix: add finalizers to cleanup cluster scoped resources on stack dele…
  pkg/controllers/monitoring/monitoring-stack/alertmanager.go
  pkg/controllers/monitoring/monitoring-stack/components.go
  pkg/controllers/monitoring/monitoring-stack/controller.go
Labels: lgtm, approved
