Repository rhobs/observability-operator, pull requests merged in 2024-04, with the labels that each got.

#454 chore: fix assertAlertmanagersAreResilientToDisruption()
  test/e2e/monitoring_stack_controller_test.go
Labels: lgtm, approved

#452 feat: make Thanos querier compliant with restricted policy
  pkg/controllers/monitoring/monitoring-stack/alertmanager.go
  pkg/controllers/monitoring/monitoring-stack/components.go
  pkg/controllers/monitoring/thanos-querier/components.go
Labels: lgtm, approved

#453 chore: enable gci linter
  .github/tools
  .golangci.yml
  Makefile.tools
  cmd/operator/main.go
  pkg/assets/loader.go
  pkg/controllers/monitoring/monitoring-stack/alertmanager.go
  pkg/controllers/monitoring/monitoring-stack/components.go
  pkg/controllers/monitoring/monitoring-stack/components_test.go
  pkg/controllers/monitoring/monitoring-stack/conditions.go
  pkg/controllers/monitoring/monitoring-stack/conditions_test.go
  pkg/controllers/monitoring/monitoring-stack/controller.go
  pkg/controllers/monitoring/thanos-querier/controller.go
  pkg/eventsource/ticker.go
  pkg/operator/operator.go
  pkg/operator/scheme.go
  test/e2e/framework/assertions.go
  test/e2e/framework/framework.go
  test/e2e/framework/monitoring_stack.go
  test/e2e/main_test.go
  test/e2e/monitoring_stack_controller_test.go
  test/e2e/prometheus_operator_test.go
  test/e2e/thanos_querier_controller_test.go
Labels: lgtm, approved

#450 apis: provide option to enable otlp/http receiver
  bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
  docs/api.md
  pkg/apis/monitoring/v1alpha1/types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/monitoring/monitoring-stack/components.go
  test/e2e/monitoring_stack_controller_test.go
Labels: lgtm, approved

#460 COO-117: fix: remove invalid owner ref on cluster role
  pkg/controllers/monitoring/monitoring-stack/alertmanager.go
  pkg/reconciler/reconciler.go
Labels: lgtm, jira/valid-reference, approved

#465 COO-117: test: add test to detect OwnerRefInvalidNamespace event
  test/e2e/framework/assertions.go
  test/e2e/main_test.go
Labels: lgtm, jira/valid-reference, approved

#434 feat: Add ObservabilityUI plugins API
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  cmd/operator/main.go
  deploy/crds/common/kustomization.yaml
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  deploy/olm/bases/observability-operator.clusterserviceversion.yaml
  deploy/operator/kustomization.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  docs/api.md
  docs/user-guides/observability-ui-plugins.md
  go.mod
  go.sum
  pkg/apis/uiplugin/v1alpha1/register.go
  pkg/apis/uiplugin/v1alpha1/types.go
  pkg/apis/uiplugin/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/compatibility_matrix_test.go
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/plugin_info_builder.go
  pkg/operator/operator.go
  pkg/operator/scheme.go
  pkg/reconciler/reconciler.go
  test/e2e/main_test.go
Labels: lgtm, approved, ok-to-test

#472 chore(release): 0.2.0
  CHANGELOG.md
  VERSION
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/kustomization.yaml
  deploy/package-operator/operator/kustomization.yaml
Labels: lgtm, approved

#448 test: prometheus scale down e2e test
  test/e2e/framework/assertions.go
  test/e2e/monitoring_stack_controller_test.go
Labels: lgtm, approved

#473 test: stablize Controller_reverts_back_changes_to_Prometheus
  test/e2e/monitoring_stack_controller_test.go
Labels: lgtm, approved
