Repository rhobs/observability-operator, pull requests merged in 2024-08, with the labels that each got.

#540 COO-261: Support tolerations and nodeselector in Monitoringstack
  bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
  docs/api.md
  pkg/apis/monitoring/v1alpha1/types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/monitoring/monitoring-stack/alertmanager.go
  pkg/controllers/monitoring/monitoring-stack/components.go
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#544 chore(release): 0.3.5
  CHANGELOG.md
  VERSION
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/kustomization.yaml
  deploy/package-operator/operator/kustomization.yaml
Labels: lgtm, approved

#545 feat: update RBAC to include listing TempoMonolithic CRs
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/distributed_tracing.go
Labels: lgtm, approved, needs-ok-to-test

#543 chore: add tests for plugin compatibility matrix
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/compatibility_matrix_test.go
Labels: lgtm, approved

#546 docs: UIPlugin updates
  docs/user-guides/observability-ui-plugins.md
Labels: lgtm, approved, needs-ok-to-test

#554 chore: update uiplugins release versions
  cmd/operator/main.go
Labels: lgtm, approved, ok-to-test

#555 chore: update korrel8r image versions
  cmd/operator/main.go
Labels: lgtm, approved

#556 build: add api-support annotations to monitoring CRDs
  bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
  bundle/manifests/monitoring.rhobs_alertmanagers.yaml
  bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
  bundle/manifests/monitoring.rhobs_podmonitors.yaml
  bundle/manifests/monitoring.rhobs_probes.yaml
  bundle/manifests/monitoring.rhobs_prometheusagents.yaml
  bundle/manifests/monitoring.rhobs_prometheuses.yaml
  bundle/manifests/monitoring.rhobs_prometheusrules.yaml
  bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
  bundle/manifests/monitoring.rhobs_servicemonitors.yaml
  bundle/manifests/monitoring.rhobs_thanosqueriers.yaml
  bundle/manifests/monitoring.rhobs_thanosrulers.yaml
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
  deploy/crds/common/monitoring.rhobs_thanosqueriers.yaml
  deploy/dependencies/kustomization.yaml
  deploy/dependencies/patches/api-support-experimental-annotation.yaml
  deploy/dependencies/patches/api-support-techpreview-annotation.yaml
  pkg/apis/monitoring/v1alpha1/types.go
Labels: lgtm, approved

#557 docs: fix UI docs
  docs/user-guides/observability-ui-plugins.md
Labels: lgtm, approved, ok-to-test

#558 build: update prometheus-operator manifests to 0.75.2
  bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
  bundle/manifests/monitoring.rhobs_alertmanagers.yaml
  bundle/manifests/monitoring.rhobs_podmonitors.yaml
  bundle/manifests/monitoring.rhobs_probes.yaml
  bundle/manifests/monitoring.rhobs_prometheusagents.yaml
  bundle/manifests/monitoring.rhobs_prometheuses.yaml
  bundle/manifests/monitoring.rhobs_prometheusrules.yaml
  bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
  bundle/manifests/monitoring.rhobs_servicemonitors.yaml
  bundle/manifests/monitoring.rhobs_thanosrulers.yaml
  bundle/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml
  bundle/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml
  bundle/manifests/obo-prometheus-operator_v1_service.yaml
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/dependencies/kustomization.yaml
Labels: lgtm, approved

#559 chore(release): 0.4.0
  CHANGELOG.md
  VERSION
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/kustomization.yaml
  deploy/package-operator/operator/kustomization.yaml
Labels: lgtm, approved
