Repository rhobs/observability-operator, pull requests merged in 2024-06, with the labels that each got.

#480 COO-169: feat: add troubleshooting panel and distributed tracing ui-plugin
  Makefile.tools
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  cmd/operator/main.go
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  docs/api.md
  docs/user-guides/observability-ui-plugins.md
  pkg/apis/uiplugin/v1alpha1/types.go
  pkg/apis/uiplugin/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/compatibility_matrix_test.go
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/distributed_tracing.go
  pkg/controllers/uiplugin/plugin_info_builder.go
  pkg/controllers/uiplugin/troubleshooting_panel.go
  pkg/operator/operator.go
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#477 feat: support logging as ui-plugin
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  cmd/operator/main.go
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  docs/api.md
  pkg/apis/uiplugin/v1alpha1/types.go
  pkg/apis/uiplugin/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/compatibility_matrix_test.go
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/logging.go
  pkg/controllers/uiplugin/plugin_info_builder.go
Labels: lgtm, approved

#499 fix: compatibility matrix unit tests
  pkg/controllers/uiplugin/compatibility_matrix_test.go
Labels: lgtm, approved

#497 Korrel8r backend creation when the troubleshooting panel is deployed
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  cmd/operator/main.go
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  docs/api.md
  docs/user-guides/observability-ui-plugins.md
  pkg/apis/uiplugin/v1alpha1/types.go
  pkg/apis/uiplugin/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/config/korrel8r.yaml
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/plugin_info_builder.go
  pkg/controllers/uiplugin/troubleshooting_panel.go
Labels: lgtm, approved

#501 COO-179: fix: compatibility matrix version validation
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/compatibility_matrix_test.go
Labels: lgtm, jira/valid-reference, approved

#504 COO-180: fix: bind service with correct container port for korrel8r
  pkg/controllers/uiplugin/components.go
Labels: lgtm, jira/valid-reference, approved

#503 COO-181: fix: Change only the console plugins to avoid mutating existing cluster configuration
  pkg/controllers/uiplugin/controller.go
Labels: lgtm, jira/valid-reference, approved

#505 COO-183: Prevent Reconcile Loop for Troubleshooting Panel UIPlugin
  pkg/controllers/uiplugin/troubleshooting_panel.go
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#500 chore: edit OWNERS maintainers
  OWNERS_ALIASES
Labels: lgtm, approved

#502 fix: update distributed_tracing.go to include a service proxy
  pkg/controllers/uiplugin/distributed_tracing.go
Labels: lgtm, approved, ok-to-test

#506 chore(release): 0.3.0
  CHANGELOG.md
  VERSION
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/kustomization.yaml
  deploy/package-operator/operator/kustomization.yaml
Labels: lgtm, approved

#510 fix: shellcheck wrong curl
  Makefile.tools
Labels: lgtm, approved

#507 chore(release): 0.3.1
  CHANGELOG.md
  VERSION
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/kustomization.yaml
  deploy/package-operator/operator/kustomization.yaml
Labels: lgtm, approved

#515 COO-186: fix: add korrel8r proxy configuration to logging view plugin
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/logging.go
Labels: lgtm, jira/valid-reference, approved

#516 Bump go 1.22
  .github/e2e-tests-olm/action.yaml
  build/Dockerfile
  bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
  bundle/manifests/monitoring.rhobs_thanosqueriers.yaml
  deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
  deploy/crds/common/monitoring.rhobs_thanosqueriers.yaml
  docs/api.md
  go.mod
  go.sum
  pkg/eventsource/ticker.go
  test/Dockerfile
Labels: lgtm, approved

#519 chore: update GitHub actions to setup-go@v5
  .github/e2e-tests-olm/action.yaml
  .github/olm-publish/action.yaml
  .github/osd-test-harness-publish/action.yaml
  .github/package-operator-publish/action.yaml
  .github/tools-cache/action.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/release.yaml
Labels: lgtm, approved

#518 feat: bump Prometheus operator to v0.74.0
  bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
  bundle/manifests/monitoring.rhobs_alertmanagers.yaml
  bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
  bundle/manifests/monitoring.rhobs_podmonitors.yaml
  bundle/manifests/monitoring.rhobs_probes.yaml
  bundle/manifests/monitoring.rhobs_prometheusagents.yaml
  bundle/manifests/monitoring.rhobs_prometheuses.yaml
  bundle/manifests/monitoring.rhobs_prometheusrules.yaml
  bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
  bundle/manifests/monitoring.rhobs_servicemonitors.yaml
  bundle/manifests/monitoring.rhobs_thanosrulers.yaml
  bundle/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml
  bundle/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml
  bundle/manifests/obo-prometheus-operator_v1_service.yaml
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
  deploy/dependencies/kustomization.yaml
  docs/api.md
  go.mod
  go.sum
  pkg/controllers/monitoring/monitoring-stack/components.go
  test/e2e/monitoring_stack_controller_test.go
Labels: lgtm, approved

#520 chore(release): 0.3.2
  CHANGELOG.md
  VERSION
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/kustomization.yaml
  deploy/package-operator/operator/kustomization.yaml
Labels: lgtm, approved

#521 fix: return the right loki service names
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/troubleshooting_panel.go
Labels: lgtm, approved

#481 feat: restrict UIPlugin CRD names to allow a single instance per type
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  pkg/apis/uiplugin/v1alpha1/types.go
Labels: lgtm, approved

#517 Add Clusterrole to allow Korrel8r to view all signal data
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  cmd/operator/main.go
  deploy/operator/observability-operator-cluster-role.yaml
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/troubleshooting_panel.go
Labels: lgtm, approved

#522 chore(release): 0.3.3
  CHANGELOG.md
  VERSION
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/kustomization.yaml
  deploy/package-operator/operator/kustomization.yaml
Labels: lgtm, approved
