Repository rhobs/observability-operator, pull requests merged in 2024-09, with the labels that each got.

#561 docs: fix dashboard plugin name in example
  docs/user-guides/observability-ui-plugins.md
Labels: lgtm, approved, ok-to-test

#562 docs: fix COO version to show future versions in uiplugins docs
  docs/user-guides/observability-ui-plugins.md
Labels: lgtm, approved, ok-to-test

#567 chore: remove calls to deprecated AddToScheme()
  pkg/operator/scheme.go
Labels: lgtm, approved

#560 chore: flag PrometheusAgent CRD as internal
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/bases/observability-operator.clusterserviceversion.yaml
  deploy/package-operator/dependencies/kustomization.yaml
Labels: lgtm, approved

#566 chore: update tools
  .github/tools
  .golangci.yml
  Makefile.tools
  bundle.Dockerfile
  bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
  bundle/manifests/monitoring.rhobs_thanosqueriers.yaml
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  bundle/metadata/annotations.yaml
  deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
  deploy/crds/common/monitoring.rhobs_thanosqueriers.yaml
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  docs/api.md
  go.mod
Labels: lgtm, approved

#565 COO-356: remove link to rhobs-handbook.netlify.app
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/bases/observability-operator.clusterserviceversion.yaml
Labels: lgtm, jira/valid-reference, approved

#576 COO-152: fix: Add finalizer to cleanup the console after UIPlugin is deleted
  pkg/controllers/uiplugin/compatibility_matrix_test.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/distributed_tracing.go
  pkg/controllers/uiplugin/logging.go
  pkg/controllers/uiplugin/plugin_info_builder.go
  pkg/controllers/uiplugin/troubleshooting_panel.go
Labels: lgtm, jira/valid-reference, approved

#531 test: enable OCP mode and add auto case for uiplugin dashboard
  test/e2e/framework/assertions.go
  test/e2e/framework/framework.go
  test/e2e/main_test.go
  test/e2e/uiplugin_test.go
  test/osd-e2e.sh
  test/run-e2e-ocp.sh
  test/run-e2e.sh
Labels: lgtm, approved
