Repository rhobs/observability-operator, pull requests merged in 2024-11, with the labels that each got.

#614 feat: add basic gather script for monitoring components
  build/Dockerfile
  must-gather/README.md
  must-gather/collection-scripts/common.sh
  must-gather/collection-scripts/gather
Labels: lgtm, approved

#611 COO-481: feat: require TLS client certificate for /metrics
  cmd/operator/main.go
  pkg/operator/operator.go
  test/e2e/framework/assertions.go
  test/e2e/framework/framework.go
Labels: lgtm, jira/valid-reference, approved

#616 feat: add operator controller to add ServiceMonitor
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  go.mod
  go.sum
  pkg/controllers/operator/components.go
  pkg/controllers/operator/controller.go
  pkg/operator/operator.go
Labels: lgtm, approved

#619 operator: register scheme in operator
  pkg/controllers/operator/controller.go
  pkg/operator/scheme.go
Labels: lgtm, approved

#621 chore: add observability ui team members to contributors
  OWNERS_ALIASES
Labels: lgtm, approved, needs-ok-to-test

#623 COO-526: fix: allow operator SA to create/update events
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  pkg/controllers/doc.go
Labels: lgtm, jira/valid-reference, approved

#624 chore: add LICENSE file
  LICENSE
Labels: lgtm, approved

#625 COO-526: disable events from the serving certificate controller
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  pkg/controllers/doc.go
  pkg/operator/operator.go
Labels: lgtm, jira/valid-reference, approved

#620 COO-525: fix the creation of the operator's ServiceMonitor resource when not running in the default namespace
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  pkg/controllers/operator/components.go
  pkg/controllers/operator/controller.go
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/troubleshooting_panel.go
  pkg/reconciler/reconciler.go
  test/e2e/framework/assertions.go
  test/e2e/metrics_test.go
Labels: lgtm, jira/valid-reference, approved

#628 COO-483: feat: add "Enable cluster monitoring" checkbox to OCP console
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/bases/observability-operator.clusterserviceversion.yaml
Labels: lgtm, jira/valid-reference, approved

#629 COO-485: feat: deploy PrometheusRule resource
  .github/tools
  .github/workflows/pr-checks.yaml
  Makefile
  Makefile.tools
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/monitoring/kustomization.yaml
  deploy/monitoring/monitoring-alertmanager-rules.yaml
  deploy/monitoring/monitoring-prometheus-operator-rules.yaml
  deploy/monitoring/monitoring-prometheus-rules.yaml
  deploy/monitoring/observability-operator-rules.yaml
  jsonnet/OWNERS
  jsonnet/common.libsonnet
  jsonnet/components/alertmanager/alertmanager-rules.jsonnet
  jsonnet/components/alertmanager/main.jsonnet
  jsonnet/components/prometheus-operator/main.jsonnet
  jsonnet/components/prometheus-operator/prometheus-operator-rules.jsonnet
  jsonnet/components/prometheus/main.jsonnet
  jsonnet/components/prometheus/prometheus-rules.jsonnet
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  test/e2e/operator_metrics_test.go
Labels: lgtm, jira/valid-reference, approved

#626 chore: update korrel8r release version
  cmd/operator/main.go
Labels: lgtm, approved

#630 chore: add suggested namespace to bundle
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/bases/observability-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#631 COO-485: chore: remove legacy PrometheusRule resources
  bundle/manifests/observability-operator-alertmanager-rules_monitoring.coreos.com_v1_prometheusrule.yaml
  bundle/manifests/observability-operator-prometheus-operator-rules_monitoring.coreos.com_v1_prometheusrule.yaml
  bundle/manifests/observability-operator-prometheus-rules_monitoring.coreos.com_v1_prometheusrule.yaml
  bundle/manifests/observability-operator-rules_monitoring.coreos.com_v1_prometheusrule.yaml
  bundle/manifests/observability-operator_monitoring.coreos.com_v1_prometheusrule.yaml
Labels: lgtm, jira/valid-reference, approved
