Repository rhobs/observability-operator, pull requests merged in 2025-03, with the labels that each got.

#691 chore: update Health Analyzer release version
  cmd/operator/main.go
  docs/user-guides/observability-ui-plugins.md
Labels: lgtm, approved, needs-ok-to-test

#690 feat: discover default lokistack
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  docs/api.md
  pkg/apis/uiplugin/v1alpha1/types.go
  pkg/apis/uiplugin/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/dashboards.go
  pkg/controllers/uiplugin/logging.go
  pkg/controllers/uiplugin/plugin_info_builder.go
Labels: lgtm, approved

#693 Sync main
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  cmd/operator/main.go
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  docs/api.md
  docs/user-guides/observability-ui-plugins.md
  pkg/apis/uiplugin/v1alpha1/types.go
  pkg/apis/uiplugin/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/dashboards.go
  pkg/controllers/uiplugin/logging.go
  pkg/controllers/uiplugin/plugin_info_builder.go
Labels: approved

#695 fix: test script failure when enable OCP feature gate
  test/run-e2e-ocp.sh
Labels: lgtm, approved

#699 fix: tls configuration for perses and perses client
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/perses.dev_perses.yaml
  cmd/operator/main.go
  deploy/operator/kustomization.yaml
  deploy/perses/crds/perses.dev_perses.yaml
  deploy/perses/perses-operator-deployment.yaml
  go.mod
  go.sum
  pkg/controllers/uiplugin/monitoring.go
Labels: lgtm, approved

#702 COO-739: fix: set tech preview support level for the monitoring plugin
  docs/user-guides/observability-ui-plugins.md
  pkg/controllers/uiplugin/compatibility_matrix.go
Labels: lgtm, jira/valid-reference, approved

#706 chore: set operator version to 1.1.0 for bundle
  VERSION
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/kustomization.yaml
  deploy/package-operator/operator/kustomization.yaml
Labels: lgtm, approved

#708 fix: set correct perses image version
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  cmd/operator/main.go
  deploy/operator/kustomization.yaml
Labels: lgtm, approved

#707 COO-741: docs: fix contribution link in CSV
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/bases/observability-operator.clusterserviceversion.yaml
Labels: lgtm, jira/valid-reference, approved

#711 COO-713: fix: Add missing perses schemas
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/perses/perses-operator-deployment.yaml
  go.mod
  go.sum
  pkg/controllers/uiplugin/monitoring.go
Labels: lgtm, jira/valid-reference, approved

#712 COO-749 and COO-748: Fix compatibility_matrix so OCP v4.15.0-0.nightly deploys logging and distributed-tracing image containing PF5
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/compatibility_matrix_test.go
Labels: lgtm, jira/valid-reference, approved

#713 docs: fix compatibility matrix for ui plugins
  docs/user-guides/observability-ui-plugins.md
Labels: lgtm, approved

#667 OSD-28131: Deploying COO in place of OBO on SC clusters
  deploy/olm/syncselector-template.yaml
Labels: lgtm, jira/valid-reference, approved, needs-ok-to-test

#716 feat: deploying COO in place of OBO on SC clusters
  deploy/olm/syncselector-template.yaml
Labels: lgtm, approved, needs-ok-to-test

#714 docs: fix compatibility table for perses dashboards feature
  docs/user-guides/observability-ui-plugins.md
Labels: lgtm, approved

#719 fix: web UI case failure in downstream
  test/e2e/monitoring_stack_controller_test.go
Labels: lgtm, approved

#720 fix: web UI case failure in downstream (#719)
  test/e2e/monitoring_stack_controller_test.go
Labels: lgtm, approved
