Repository rhobs/observability-operator, pull requests merged in 2025-09, with the labels that each got.

#845 build: track a placeholder file in olm/observability-operator-index/
  olm/observability-operator-index/index.yaml
Labels: approved

#806 fix: remove replace command after introducing API module
  build/Dockerfile
  go.mod
  go.sum
  pkg/apis/monitoring/v1alpha1/register.go
  pkg/apis/observability/v1alpha1/register.go
  pkg/apis/uiplugin/v1alpha1/register.go
  test/Dockerfile
Labels: lgtm, approved

#847 build: fix catalog-image target
  Makefile
Labels: approved

#848 build: pass $(BUNDLE_IMG) instead of $(BUNDLE_IMAGE) to update-catalo…
  Makefile
Labels: approved

#852 build: we always want to replace the previous entry in the catalog te…
  .gitignore
  olm/observability-operator-index/index.yaml
  olm/update-channels.sh
Labels: approved

#875 COO-1185: fix version of prometheus-operator client
  go.mod
  go.sum
Labels: lgtm, jira/valid-reference, approved

#879 ci: don't run commitlint on dependabot PRs
  .github/workflows/pr-checks.yaml
Labels: lgtm, approved

#857 chore: kustomize edit fix on all kustomization.yaml
  deploy/crds/common/kustomization.yaml
  deploy/crds/kubernetes/kustomization.yaml
  deploy/dependencies/kustomization.yaml
  deploy/package-operator/crds/kustomization.yaml
  deploy/package-operator/dependencies-kubeconfig/kustomization.yaml
  deploy/package-operator/dependencies/kustomization.yaml
  deploy/perses/crds/kustomization.yaml
  deploy/samples/kustomization.yaml
  deploy/scorecard/kustomization.yaml
Labels: approved
