Repository rhobs/observability-operator, pull requests merged in 2025-05, with the labels that each got.

#725 COO-864: feat: enable pprof on the operator
  pkg/operator/operator.go
Labels: lgtm, jira/valid-reference, approved

#733 COO-818: feat: add schema configuration for logging view plugin
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  docs/api.md
  pkg/apis/uiplugin/v1alpha1/types.go
  pkg/controllers/uiplugin/logging.go
Labels: lgtm, jira/valid-reference, approved

#735 docs: add schema field for ui logging
  docs/user-guides/observability-ui-plugins.md
Labels: lgtm, approved

#736 feat: add PatternFly 5 stream for distributed tracing UI plugin and mark it as GA
  cmd/operator/main.go
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/compatibility_matrix_test.go
Labels: lgtm, approved, needs-ok-to-test

#737 fix: default image for distributed tracing new stream
  cmd/operator/main.go
Labels: lgtm, approved

#738 feat: update health-analyzer to v0.5.0
  cmd/operator/main.go
  docs/user-guides/observability-ui-plugins.md
  pkg/controllers/uiplugin/monitoring.go
  pkg/controllers/uiplugin/monitoring_test.go
Labels: lgtm, approved

#723 fix: github action failure to set up do in olm publish
  .github/olm-publish/action.yaml
Labels: lgtm, approved

#741 chore(release): 1.2.0
  CHANGELOG.md
  VERSION
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/olm/kustomization.yaml
  deploy/package-operator/operator/kustomization.yaml
Labels: lgtm, approved

#742 fix: further fix github action olm publish failure
  .github/olm-publish/action.yaml
Labels: lgtm, approved

#743 COO-760: fix: allow to create a logging plugin without a loki stack
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/logging.go
  pkg/controllers/uiplugin/plugin_info_builder.go
Labels: lgtm, jira/valid-reference, approved

#745 COO-936: build: check for go installation before setting up a new environment
  .github/olm-publish/action.yaml
Labels: lgtm, jira/valid-reference, approved

#744 COO-942: Adding deployment of common accelerator perses dashboard
  pkg/controllers/uiplugin/accelerators.go
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/monitoring.go
  pkg/operator/scheme.go
Labels: lgtm, jira/valid-reference, approved, needs-ok-to-test

#747 feat: add monitoring-plugin stream 0.4 and 0.5
  cmd/operator/main.go
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/compatibility_matrix_test.go
Labels: lgtm, approved

#748 Add CRD scaffolding for cluster observability / signal manager
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/crds/common/observability.openshift.io_clusterobservabilities.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  docs/api.md
  pkg/apis/observability/v1alpha1/register.go
  pkg/apis/observability/v1alpha1/types.go
  pkg/apis/observability/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved

#749 chore: update troubleshooting plugin image tag
  cmd/operator/main.go
Labels: lgtm, approved

#751 fix: add default value to logs schema
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  docs/api.md
  pkg/apis/uiplugin/v1alpha1/types.go
Labels: lgtm, approved

#755 chore: update troubleshooting plugin to new image
  cmd/operator/main.go
Labels: lgtm, approved

#756 chore: update logging image to v6.1.1
  cmd/operator/main.go
Labels: lgtm, approved

#773 feat: update perses operator to v0.1.12
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/perses/perses-operator-cluster-role.yaml
  deploy/perses/perses-operator-deployment.yaml
  pkg/controllers/uiplugin/monitoring.go
Labels: lgtm, approved

#774 fix: use mounted ca for perses operator client
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/perses/perses-operator-deployment.yaml
  pkg/controllers/uiplugin/monitoring.go
Labels: lgtm, approved

#775 fix: remove default value for logging as it affects other plugins
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  docs/api.md
  pkg/apis/uiplugin/v1alpha1/types.go
Labels: lgtm, approved
