Repository rhobs/observability-operator, pull requests merged in 2025-02, with the labels that each got.

#672 COO-666: Fix support annotation 1.0
  bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
  bundle/manifests/monitoring.rhobs_alertmanagers.yaml
  bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
  bundle/manifests/monitoring.rhobs_podmonitors.yaml
  bundle/manifests/monitoring.rhobs_probes.yaml
  bundle/manifests/monitoring.rhobs_prometheusagents.yaml
  bundle/manifests/monitoring.rhobs_prometheuses.yaml
  bundle/manifests/monitoring.rhobs_prometheusrules.yaml
  bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
  bundle/manifests/monitoring.rhobs_servicemonitors.yaml
  bundle/manifests/monitoring.rhobs_thanosqueriers.yaml
  bundle/manifests/monitoring.rhobs_thanosrulers.yaml
  bundle/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml
  bundle/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml
  bundle/manifests/obo-prometheus-operator_v1_service.yaml
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
  deploy/crds/common/monitoring.rhobs_thanosqueriers.yaml
  deploy/dependencies/kustomization.yaml
  pkg/apis/monitoring/v1alpha1/types.go
Labels: lgtm, jira/valid-reference, approved

#637 feat: log Kubernetes events related to TLS certificate
  pkg/operator/operator.go
Labels: lgtm, approved

#598 feat: TLS support for the Thanos web endpoint
  bundle/manifests/monitoring.rhobs_thanosqueriers.yaml
  deploy/crds/common/monitoring.rhobs_thanosqueriers.yaml
  docs/api.md
  pkg/apis/monitoring/v1alpha1/types.go
  pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/monitoring/thanos-querier/components.go
  pkg/controllers/monitoring/thanos-querier/controller.go
  test/e2e/framework/assertions.go
  test/e2e/thanos_querier_controller_test.go
Labels: lgtm, approved, needs-ok-to-test

#664 feat: OU-571 Add Perses and Incidents Feature Flags
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  docs/api.md
  docs/user-guides/observability-ui-plugins.md
  pkg/apis/uiplugin/v1alpha1/types.go
  pkg/apis/uiplugin/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/compatibility_matrix_test.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/monitoring.go
  pkg/controllers/uiplugin/monitoring_test.go
  pkg/controllers/uiplugin/plugin_info_builder.go
Labels: lgtm, approved

#677 NO-JIRA: remove acm-version check for acm-alerting ui feature
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  go.mod
  go.sum
  pkg/controllers/uiplugin/compatibility_matrix_test.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/monitoring.go
  pkg/controllers/uiplugin/monitoring_test.go
  pkg/controllers/uiplugin/plugin_info_builder.go
  pkg/operator/scheme.go
Labels: lgtm, jira/valid-reference, approved

#675 Bump deps 25 02 20
  build/Dockerfile
  go.mod
  go.sum
Labels: approved

#676 chore: update obo-prometheus-operator to v0.80.1
  bundle/manifests/monitoring.rhobs_alertmanagerconfigs.yaml
  bundle/manifests/monitoring.rhobs_alertmanagers.yaml
  bundle/manifests/monitoring.rhobs_monitoringstacks.yaml
  bundle/manifests/monitoring.rhobs_podmonitors.yaml
  bundle/manifests/monitoring.rhobs_probes.yaml
  bundle/manifests/monitoring.rhobs_prometheusagents.yaml
  bundle/manifests/monitoring.rhobs_prometheuses.yaml
  bundle/manifests/monitoring.rhobs_prometheusrules.yaml
  bundle/manifests/monitoring.rhobs_scrapeconfigs.yaml
  bundle/manifests/monitoring.rhobs_servicemonitors.yaml
  bundle/manifests/monitoring.rhobs_thanosrulers.yaml
  bundle/manifests/obo-prometheus-operator-admission-webhook_policy_v1_poddisruptionbudget.yaml
  bundle/manifests/obo-prometheus-operator-admission-webhook_v1_service.yaml
  bundle/manifests/obo-prometheus-operator_v1_service.yaml
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/crds/common/monitoring.rhobs_monitoringstacks.yaml
  deploy/dependencies/kustomization.yaml
  docs/api.md
  go.mod
  go.sum
  pkg/controllers/monitoring/monitoring-stack/components.go
  test/e2e/monitoring_stack_controller_test.go
Labels: lgtm, approved

#681 NO-JIRA: update docs with new monitoring UIPlugin schema
  docs/user-guides/observability-ui-plugins.md
Labels: lgtm, jira/valid-reference, approved

#680 add Perses operator deployment and apis
  Makefile
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_uiplugins.yaml
  bundle/manifests/perses.dev_perses.yaml
  bundle/manifests/perses.dev_persesdashboards.yaml
  bundle/manifests/perses.dev_persesdatasources.yaml
  cmd/operator/main.go
  deploy/crds/common/observability.openshift.io_uiplugins.yaml
  deploy/olm/bases/observability-operator.clusterserviceversion.yaml
  deploy/olm/kustomization.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  deploy/perses/crds/kustomization.yaml
  deploy/perses/crds/perses.dev_perses.yaml
  deploy/perses/crds/perses.dev_persesdashboards.yaml
  deploy/perses/crds/perses.dev_persesdatasources.yaml
  deploy/perses/kustomization.yaml
  deploy/perses/perses-operator-cluster-role-binding.yaml
  deploy/perses/perses-operator-cluster-role.yaml
  deploy/perses/perses-operator-deployment.yaml
  deploy/perses/perses-operator-service-account.yaml
  deploy/samples/ui-monitoring-plugin.yaml
  docs/api.md
  docs/user-guides/observability-ui-plugins.md
  go.mod
  go.sum
  pkg/apis/uiplugin/v1alpha1/types.go
  pkg/apis/uiplugin/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/controller.go
  pkg/controllers/uiplugin/monitoring.go
  pkg/controllers/uiplugin/monitoring_test.go
  pkg/controllers/uiplugin/plugin_info_builder.go
  pkg/operator/scheme.go
Labels: lgtm, approved

#687 OU-549: Update UIPlugin quay images in preparation for COO 1.1 release
  cmd/operator/main.go
Labels: lgtm, jira/valid-reference, approved

#688 drop support for ui monitoring 4.14
  pkg/controllers/uiplugin/compatibility_matrix.go
  pkg/controllers/uiplugin/compatibility_matrix_test.go
Labels: lgtm, approved
