Repository rhobs/observability-operator, pull requests merged in 2025-10, with the labels that each got.

#889 COO-1248: fix: use apiReader for correct ui plugin registration
  pkg/controllers/uiplugin/components.go
  pkg/controllers/uiplugin/controller.go
Labels: lgtm, jira/valid-reference, approved

#884 fix: sync Perses CRD with perses-operator
  bundle/manifests/perses.dev_perses.yaml
  deploy/perses/crds/perses.dev_perses.yaml
Labels: lgtm, approved, ok-to-test

#891 chore: update log message
  pkg/controllers/monitoring/thanos-querier/controller.go
Labels: lgtm, approved

#885 chore: rename ClusterObservability to ObsevervabilityInstaller
  build/Dockerfile
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  bundle/manifests/observability.openshift.io_observabilityinstallers.yaml
  cmd/operator/main.go
  deploy/crds/common/kustomization.yaml
  deploy/crds/common/observability.openshift.io_observabilityinstallers.yaml
  deploy/operator/observability-operator-cluster-role.yaml
  docs/api.md
  docs/observabilityinstaller.md
  go.mod
  go.sum
  pkg/apis/observability/v1alpha1/register.go
  pkg/apis/observability/v1alpha1/types.go
  pkg/apis/observability/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/observability/observability_controller.go
  pkg/controllers/observability/otel_components.go
  pkg/controllers/observability/reconcilers.go
  pkg/controllers/observability/reconcilers_test.go
  pkg/controllers/observability/tempo_components.go
  pkg/operator/operator.go
  test/Dockerfile
  test/e2e/observability_installer_test.go
Labels: lgtm, approved

#899 COO-1252: chore: fix flaky ObservabilityInstaller tests
  test/e2e/observability_installer_test.go
  test/e2e/traces_telemetrygen.yaml
  test/e2e/traces_tempo_readiness.yaml
Labels: lgtm, jira/valid-reference, approved

#900 chore: improve ObservabilityInstaller docs
  docs/observabilityinstaller.md
Labels: lgtm, approved

#893 chore: update Thanos Querier documentation
  bundle/manifests/monitoring.rhobs_thanosqueriers.yaml
  bundle/manifests/observability-operator.clusterserviceversion.yaml
  deploy/crds/common/monitoring.rhobs_thanosqueriers.yaml
  docs/api.md
  pkg/apis/monitoring/v1alpha1/types.go
Labels: lgtm, approved

#903 fix: observabilityinstaller fix AWS STS config
  pkg/controllers/observability/tempo_components.go
Labels: lgtm, approved
